### ISSUE TITLE
Failure running `brew install` on macOS 10.14.3

### ISSUE THREAD

**Issue by bjhomer** [samdmarshall/nslocalizer#11]
Bug: Permission failures on `brew install` due to system protections present on macOS 10.13+

---

**Description**:

When I try to install via `brew install`, I get the following errors:

```
$ brew install samdmarshall/formulae/nslocalizer
==> Installing nslocalizer from samdmarshall/formulae
==> Cloning https://github.com/samdmarshall/nslocalizer.git
Updating /Users/bjhomer/Library/Caches/Homebrew/nslocalizer--git
==> Checking out branch develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.
HEAD is now at 4c00aa1 Merge pull request #10 from samdmarshall/updating-pbPlist-version
Entering 'docs'
/Users/bjhomer/Library/Caches/Homebrew/nslocalizer--git/docs
==> pip3 install -r install_requirements.txt
Last 15 lines from /Users/bjhomer/Library/Logs/Homebrew/nslocalizer/01.pip3:
  Building wheel for pbPlist (setup.py): finished with status 'done'
  Stored in directory: /private/tmp/nslocalizer-20190225-22020-mnpzab/.brew_home/Library/Caches/pip/wheels/7a/8e/c5/1222a694fb77543c4a19a9a783ce962abd63f0ad3eff749cb9
  Building wheel for langcodes (setup.py): started
  Building wheel for langcodes (setup.py): finished with status 'done'
  Stored in directory: /private/tmp/nslocalizer-20190225-22020-mnpzab/.brew_home/Library/Caches/pip/wheels/84/20/3d/dc2010b4f7c0b786a06947530a962972caead0c58898f25a02
  Building wheel for biplist (setup.py): started
  Building wheel for biplist (setup.py): finished with status 'done'
  Stored in directory: /private/tmp/nslocalizer-20190225-22020-mnpzab/.brew_home/Library/Caches/pip/wheels/e1/a5/ce/28ba6a80c2487f54deec4a2eda7ccda8bcbeeec2aad39e9779
  Building wheel for marisa-trie (setup.py): started
  Building wheel for marisa-trie (setup.py): finished with status 'done'
  Stored in directory: /private/tmp/nslocalizer-20190225-22020-mnpzab/.brew_home/Library/Caches/pip/wheels/45/24/79/022624fc914f0e559fe8a1141aaff1f9df810905a13fc75d57
Successfully built pbPlist langcodes biplist marisa-trie
Installing collected packages: pyobjc-core, pyobjc-framework-Cocoa, biplist, pbPlist, marisa-trie, langcodes
Could not install packages due to an EnvironmentError: [Errno 1] Operation not permitted: '/usr/local/lib/python3.7/site-packages/pyobjc_core-5.1.2-py3.7-nspkg.pth'


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/samdmarshall/homebrew-formulae/issues
```

It appears that `/usr/local/lib/python3.7` is protected when running `brew install` for some reason, and it's causing problems with the `pip3 install` command in the nslocalizer brew formula. I've checked that the permissions on the directory are correct, but installation still fails. I was able to get around it by manually running `pip3 install pyobjc-core, pyobjc-framework-Cocoa, biplist, pbPlist, marisa-trie, langcodes`, but most users won't know to do that. And even after doing that, I had trouble when trying to update to a newer version of nslocalizer.

This is likely the same cause behind issue #7.

A possible solution is to pass the `--user` flag to `pip3 install`. When I modified the home-brew formula to pass that flag, installation succeeded and the issues were resolved. Passing `--user` does limit the functionality to the current user, but that seems to mostly be the default behavior of `homebrew` anyway, so that's probably fine?

**Comment by bjhomer** [comment]
Hm… on second look, passing `--user` caused installation to succeed, but now it's not running correctly, and I don't see the `pip`-installed packages in either the system directory or the home one. It may be installing into its own environment.

It looks like this document may be relevant: https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md

**Comment by samdmarshall** [comment]
shouldn't the python3 site-packages be writable? how else is it supposed to work?

**Comment by bjhomer** [comment]
I would think so, but I think the sandboxing that homebrew is using is preventing it

**Comment by bjhomer** [comment]
Or perhaps homebrew is setting up a virtualenv that is interfering

**Comment by samdmarshall** [comment]
looking over the document you linked I am only left thinking "what the heck?!?!". so, am I supposed to declare and write out the URLs and hashes to each of the libraries that need to be installed as dependencies for homebrew to be able to run and install?? if that is the case then I might just switch to using pip for distribution instead because that seems completely bonkers.

**Comment by bjhomer** [comment]
Yeah, that's what it looks like to me. If using pip for distribution is significantly easier, I'd say go for that.

**Comment by samdmarshall** [comment]
okay well I cannot hope to start on that until the next weekend; I hope everyone that runs into this can wait until then or just install from the git repo if they are saddled with python 3.7.

**Comment by samdmarshall** [comment]
okay, it is now published via pip `pip3 install nslocalizer` instead of my homebrew tap. let me know if there are any more issues.
