### ISSUE TITLE
ignore language option does not take effect

### ISSUE THREAD

**Issue by jinjorge** [samdmarshall/nslocalizer#6]
**Type of issue**: [ Bug ]

---

**Description**: When using the `--ignore <language>` option, the language selected to ignore is still listed in the results
---

Standard `--find-missing`
```
➜  imu git:(master) nslocalizer --project Qrof.xcodeproj --target Qrof --find-missing
Base.lproj/Localizable.strings:24: warning: String "lbl_verify_email_1" missing for: Spanish, Korean, Traditional Chinese, Italian, French, German, Simplified Chinese
```

With `--ignore` option
```
➜  imu git:(master) nslocalizer --project Qrof.xcodeproj --target Qrof --ignore French --find-missing
Base.lproj/Localizable.strings:24: warning: String "lbl_verify_email_1" missing for: Italian, French, Simplified Chinese, German, Spanish, Korean, Traditional Chinese
```

**Comment by samdmarshall** [comment]
Does it not ignore the languages when you specify the short code? So for example, if you wanted it to ignore French it expects:

```
nslocalizer --project Qrof.xcodeproj --target Qrof --ignore fr --find-missing
```

**Comment by jinjorge** [comment]
Didn't cross my mind to try the short code.  The option works when specifying short code. 

```
nslocalizer --project Qrof.xcodeproj --target Qrof --ignore fr --find-missing
Base.lproj/Localizable.strings:24: warning: String "lbl_verify_email_1" missing for: Simplified Chinese, Traditional Chinese, Spanish, Korean, German, Italian
```

Feel free to close the bug or change it to an enhancement request.

Thanks!

**Comment by samdmarshall** [comment]
Great! I will file as an enhancement, because while it is documented in the usage text -- I will have a look at adding support for the full language name as well. Thanks for filing this!

**Comment by jinjorge** [comment]
Thanks for looking into it!!
